In [15]:
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
from datetime import datetime, timedelta
from geopy.distance import geodesic


df = pd.read_csv('usuarios.csv', encoding='utf-8')
ids = np.unique(df['ID'])

df2 = pd.read_csv('trayectos_20_min.csv')
coord_ini = df2['Coordenadas_inicio']
coord_fin = df2['Coordenadas_fin']

In [24]:
# comenzamos a inventarnos datos

motivo = ['Estudios', 'Trabajo', 'Deporte', 'Ocio', 'Otro']
nombre_rutina_deporte = ['Fútbol', 'Baloncesto', 'Yoga', 'Gym', 'Tenis', 'Pádel', 'Baile']

disponibilidad = ['Coche', 'Pasajero', 'Coche y pasajero']
dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
ant_trayecto = ['Bus', 'Metro', 'Tren', 'Coche', 'Coche', 'Coche', 'Coche']
horas_salida = ['7:00', '7:15', '7:30', '7:45', '8:00', '8:30', '9:00', '10:00', '11:00', '12:00', 
                '15:00', '16:00', '17:00', '17:30', '18:00', '18:30', '19:00', '20:00', '21:00']


nombre_rutina = []
id_usuario = []
lugar_salida = []
lugar_llegada = []
hora_salida = []
hora_llegada = []
motive = []
days = []
disp = []
viejo_trayecto = []



for i in range(70000):
    id_usuario.append(random.choice(ids))
    
    
    i = random.randint(0, 3499)
    lugar_salida.append(coord_ini[i][1:-1])
    lugar_llegada.append(coord_fin[i][1:-1])
    
    distancia_km = geodesic(coord_ini[i][1:-1], coord_fin[i][1:-1]).km
    tiempo_min = (distancia_km / 40) * 60 
    
    hora_sal = random.choice(horas_salida)
    hora_salida.append(hora_sal)
    hora_inicial_dt = datetime.strptime(hora_sal, '%H:%M')
    hora_final_dt = hora_inicial_dt + timedelta(minutes=tiempo_min)
    hora_final = hora_final_dt.strftime('%H:%M')
    hora_llegada.append(hora_final)

    
    m = random.choice(motivo)
    motive.append(m)
    
    if m == 'Estudios':
        d = random.choice(dias[:5])
        nom_rut = f'Estudios_universidad_{d.lower()}' # solo cogemos a que estudien en universidades
    elif m == 'Otro':
        d = random.choice(dias)
        nom_rut = f'[Indefinido]_{d.lower()}'
    elif m == 'Trabajo':
        d = random.choice(dias[:5])
        nom_rut = f'Trabajo_{d.lower()}'
    elif m == 'Ocio':
        d = random.choice(dias)
        nom_rut = f'Ocio_{d.lower()}'
    else:                                   # es deporte
        d = random.choice(dias)
        deport = random.choice(nombre_rutina_deporte)
        nom_rut = f'Deporte_{deport.lower()}_{d.lower()}'
    
    days.append(d)
    nombre_rutina.append(nom_rut)
    disp.append(random.choice(disponibilidad))
    viejo_trayecto.append(random.choice(ant_trayecto))

In [25]:
d = {'Nombre_rutina':nombre_rutina, 'Id_usuario': id_usuario, 'Lugar_salida':lugar_salida, 'Lugar_llegada':lugar_llegada, 
     'Hora_salida':hora_salida, 'Hora_llegada':hora_llegada, 'Motivo':motive, 'Dia':days, 'Disponibilidad_coche':disp,
     'Viejo_trayecto':viejo_trayecto}

df = pd.DataFrame(d)
df.head()

,Nombre_rutina,Id_usuario,Lugar_salida,Lugar_llegada,Hora_salida,Hora_llegada,Motivo,Dia,Disponibilidad_coche,Viejo_trayecto
0,[Indefinido]_miércoles,352060,"39.53156811319583, -0.3543039532493277","39.40244610750699, -0.4065950884143955",8:00,08:22,Otro,Miércoles,Coche,Coche
1,Deporte_pádel_viernes,830428,"39.55746414566028, -0.40140952057024337","39.42213873719337, -0.42480564606297794",17:00,17:22,Deporte,Viernes,Coche,Tren
2,Deporte_tenis_miércoles,594111,"39.51505863889013, -0.469698224605178","39.395897844997684, -0.39982226106287605",19:00,19:21,Deporte,Miércoles,Pasajero,Metro
3,Deporte_baloncesto_viernes,448250,"39.53295693595691, -0.3486782038533845","39.41545479842179, -0.39054877260657395",18:30,18:50,Deporte,Viernes,Coche y pasajero,Coche
4,Ocio_martes,424797,"39.54515572204451, -0.3896018829988403","39.40249143566821, -0.39937790569950965",17:30,17:53,Ocio,Martes,Pasajero,Coche

In [27]:
#df.to_csv("trayectos.csv",index_label=None)